# Generated by Django 5.1.6 on 2025-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookdetail_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
